version: "3.8" # choose version as per your need

services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra-container
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_USER=klikpesan
      - CASSANDRA_PASSWORD=klikpesan
    volumes:
      - cassandra-data:/var/lib/cassandra

  rabbitmq1:
    image: "heidiks/rabbitmq-delayed-message-exchange"
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      - POSTGRES_USER=klikpesan
      - POSTGRES_PASSWORD=klikpesan
      - POSTGRES_DB=klikpesan
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  cassandra-data:
  redis-data:
  postgres-data:
